mqtt_bridge_node:
  ros__parameters:
    mqtt:
      client:
        protocol: 4      # MQTTv311
      connection:
        host: "localhost"
        port: 1883
        keepalive: 60
      private_path: "cmeresearch/cmexa-001"
    serializer: json:dumps
    deserializer: json:loads
    n_bridges: 3
    bridge:
      bridge1: ["mqtt_bridge.bridge:RosToMqttBridge","geometry_msgs.msg:TwistStamped","/cmexa_base_mecanum_controller/cmd_vel","~/base/cmd_vel"]
      bridge2: ["mqtt_bridge.bridge:MqttToRosBridge","geometry_msgs.msg:TwistStamped","~/mqtt/cmd_vel","/mqtt/cmd_vel"]
      bridge3: ["mqtt_bridge.bridge:RosToMqttBridge","cmeresearch_msgs.msg:TinkerStepperCommand","/cmexa_base/front_left/cmd_vel","~/base/front_left/cmd_vel"]